name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@s1
    - name: make
      run: make
      

  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@s2
    - name: run
      run: ./WaSp
      
  
  clean:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@s3
    - name: clean
      run: make clean
